<?php

return [
    'background' => [
        'Entrepreneur',
        'OFW',
    ],

    'gender' => [
        'Male',
        'Female',
    ],

    'generation' => [
        '2nd',
        '3rd',
        '4th',
    ],

    'marital_status' => [
        'Single',
        'Married',
        'Widow',
        'Widower',
        'Partner',
    ],

    'nationality' => [
        'Afghan',
        'Albanian',
        'Algerian',
        'American',
        'Andorran',
        'Angolan',
        'Antiguan and Barbudan',
        'Argentine',
        'Armenian',
        'Australian',
        'Austrian',
        'Azerbaijani',
        'Bahamian',
        'Bahraini',
        'Bangladeshi',
        'Barbadian',
        'Belarusian',
        'Belgian',
        'Belizean',
        'Beninese',
        'Bhutanese',
        'Bolivian',
        'Bosnian and Herzegovinian',
        'Botswanan',
        'Brazilian',
        'British',
        'Bruneian',
        'Bulgarian',
        'Burkinabé',
        'Burmese',
        'Burundian',
        'Cambodian',
        'Cameroonian',
        'Canadian',
        'Cape Verdean',
        'Central African',
        'Chadian',
        'Chilean',
        'Chinese',
        'Colombian',
        'Comorian',
        'Congolese',
        'Costa Rican',
        'Croatian',
        'Cuban',
        'Cypriot',
        'Czech',
        'Danish',
        'Djiboutian',
        'Dominican',
        'Dutch',
        'East Timorese',
        'Ecuadorean',
        'Egyptian',
        'Emirati',
        'Equatorial Guinean',
        'Eritrean',
        'Estonian',
        'Ethiopian',
        'Fijian',
        'Filipino',
        'Finnish',
        'French',
        'Gabonese',
        'Gambian',
        'Georgian',
        'German',
        'Ghanaian',
        'Greek',
        'Grenadian',
        'Guatemalan',
        'Guinean',
        'Guyanese',
        'Haitian',
        'Honduran',
        'Hungarian',
        'Icelandic',
        'Indian',
        'Indonesian',
        'Iranian',
        'Iraqi',
        'Irish',
        'Israeli',
        'Italian',
        'Ivorian',
        'Jamaican',
        'Japanese',
        'Jordanian',
        'Kazakh',
        'Kenyan',
        'Kiribati',
        'Kuwaiti',
        'Kyrgyz',
        'Laotian',
        'Latvian',
        'Lebanese',
        'Liberian',
        'Libyan',
        'Liechtensteiner',
        'Lithuanian',
        'Luxembourger',
        'Macedonian',
        'Malagasy',
        'Malawian',
        'Malaysian',
        'Maldivian',
        'Malian',
        'Maltese',
        'Marshallese',
        'Mauritanian',
        'Mauritian',
        'Mexican',
        'Micronesian',
        'Moldovan',
        'Monacan',
        'Mongolian',
        'Montenegrin',
        'Moroccan',
        'Mozambican',
        'Namibian',
        'Nauruan',
        'Nepalese',
        'New Zealander',
        'Nicaraguan',
        'Nigerian',
        'Nigerien',
        'North Korean',
        'Norwegian',
        'Omani',
        'Pakistani',
        'Palauan',
        'Palestinian',
        'Panamanian',
        'Papua New Guinean',
        'Paraguayan',
        'Peruvian',
        'Philippines',
        'Polish',
        'Portuguese',
        'Qatari',
        'Romanian',
        'Russian',
        'Rwandan',
        'Saint Kitts and Nevisian',
        'Saint Lucian',
        'Saint Vincentian',
        'Samoan',
        'San Marinese',
        'São Toméan',
        'Saudi',
        'Senegalese',
        'Serbian',
        'Seychellois',
        'Sierra Leonean',
        'Singaporean',
        'Slovak',
        'Slovenian',
        'Solomon Islander',
        'Somali',
        'South African',
        'South Korean',
        'Spanish',
        'Sri Lankan',
        'Sudanese',
        'Surinamese',
        'Swazi',
        'Swedish',
        'Swiss',
        'Syrian',
        'Tajik',
        'Tanzanian',
        'Thai',
        'Togolese',
        'Tongan',
        'Trinidadian and Tobagonian',
        'Tunisian',
        'Turkish',
        'Turkmen',
        'Tuvaluan',
        'Ugandan',
        'Ukrainian',
        'Uruguayan',
        'Uzbek',
        'Vanuatuan',
        'Venezuelan',
        'Vietnamese',
        'Yemeni',
        'Zambian',
        'Zimbabwean',
    ],

    'point_person' => [
        'Manager',
        'Supervisor',
    ],

    'religion' => [
        'Roman Catholic',
        'Iglesia ni Cristo',
        'Protestant/Christian (Other Denominations)',
        'Philippine Independent Church (Aglipayan)',
        'Islam',
        'Buddhism',
        'Hinduism',
        'Indigenous/Traditional Religions',
        'No Religion / Atheist / Agnostic',
        'Prefer not to say',
    ],

    'source_of_information' => [
        'Social Media',
        'PFA',
        'Franchise Exhibit',
        'Family or Friends',
    ],

    'region' => [
        'LUZ',
        'VIS',
        'MIN',
    ],
];
